[package]
name = "bf-jit"
version = "0.1.0"
authors = ["katsurahiroyuki"]
edition = "2018"
links = "libbf"
build = "build.rs"

[dependencies]
libc = "0.2"
clap = "2.32.0"
lazy_static = "1.2.0"

[build-dependencies]
gcc = "0.3"

